// ============================================================
// Cortex C8 tier-① — pure cron-in-harness helpers (Phase 1 T5).
// Tabatha "writes" a scheduled optimization task into the user's existing
// agent harness (Claude Code / Codex). MV3 cannot touch ~/.claude directly,
// so v1 GENERATES the file bundle; the user (or the desktop companion,
// later) places it. Also defines the cortex-recommendations.v1 contract the
// overnight agent writes back and the C7 dashboard imports.
// No chrome / DOM / supabase deps — unit-tested in isolation.
// ============================================================

export const RECOMMENDATIONS_SCHEMA = 'cortex-recommendations.v1';

export const RECOMMENDATION_TYPES = [
  'hotkey',           // keyboard-shortcut suggestion
  'tool-replacement', // paid → free/local swap (cost/latency win)
  'custom-code',      // script / Chrome-extension generation candidate
  'digest',           // consolidate a polling loop into a morning digest
  'other'
];

export const RECOMMENDATION_STATUSES = ['pending', 'approved', 'dismissed', 'executed'];

/**
 * Build the harness scheduled-task file bundle.
 *
 * @param {object} opts {
 *   harness: 'claude-code'|'codex',
 *   exportDir:  absolute dir the nightly ledger exports land in (Downloads),
 *   outputDir:  absolute dir the agent writes recommendations JSON into,
 *   promptVersion: e.g. 'economize-workflow.v1',
 *   promptText: full master-prompt body (versioned artifact, C6),
 *   scheduleHint: human-readable cadence, e.g. '03:30 local'
 * }
 * @returns {{harness: string, files: Array<{relPath, content}>, instructions: string}}
 */
export function buildHarnessCronBundle(opts) {
  const { harness, exportDir, outputDir, promptVersion, promptText, scheduleHint } = opts || {};
  if (harness === 'claude-code') {
    return {
      harness,
      files: [
        {
          relPath: 'scheduled-tasks/tabatha-cortex-optimize/SKILL.md',
          content: claudeCodeTask({ exportDir, outputDir, promptVersion, scheduleHint })
        },
        {
          relPath: `scheduled-tasks/tabatha-cortex-optimize/${promptVersion}.md`,
          content: promptText || ''
        }
      ],
      instructions:
        `Copy the 'scheduled-tasks' folder into your Claude Code home (usually %USERPROFILE%\\.claude\\), ` +
        `then schedule it to run daily around ${scheduleHint || '03:30'} (Claude Code scheduled tasks or any scheduler that launches 'claude').`
    };
  }
  if (harness === 'codex') {
    return {
      harness,
      files: [
        {
          relPath: 'tabatha-cortex-optimize.md',
          content:
            `# Tabatha Cortex — nightly optimization task (Codex)\n\n` +
            `Run daily around ${scheduleHint || '03:30'}.\n\n` +
            codexBody({ exportDir, outputDir, promptVersion }) +
            `\n\n---\n\n${promptText || ''}`
        }
      ],
      instructions:
        `Register this file as a recurring Codex task (or invoke it nightly via your scheduler of choice).`
    };
  }
  throw new Error(`buildHarnessCronBundle: unknown harness "${harness}"`);
}

function sharedContract({ exportDir, outputDir, promptVersion }) {
  return (
    `1. Read the NEWEST \`cortex-ledger-*.json\` in \`${exportDir}\`. It follows the ` +
    `\`cortex-ledger-export.v1\` schema: \`records[]\` are normalized observations; ` +
    `\`repeats.candidates[]\` pre-aggregates contexts seen >= 3 times (the pattern threshold — ` +
    `NEVER recommend on behavior repeated fewer than 3 times).\n` +
    `2. Apply the master prompt \`${promptVersion}.md\` (same folder) to the export.\n` +
    `3. Write your output to \`${outputDir}\\recommendations-<day>.json\` as a ` +
    `\`${RECOMMENDATIONS_SCHEMA}\` envelope:\n` +
    '```json\n' +
    `{ "schema": "${RECOMMENDATIONS_SCHEMA}", "recommendations": [ { "id": "...", ` +
    `"type": "hotkey|tool-replacement|custom-code|digest|other", "title": "...", ` +
    `"rationale": "...", "evidence": [{"key": "...", "count": 0}], ` +
    `"expectedSavings": "...", "status": "pending" } ] }\n` +
    '```\n' +
    `4. The user imports that file in Tabatha's Cortex panel (read-only dashboard, approve/dismiss).\n` +
    `5. Personal-partition records stay personal: do not upload the ledger anywhere.`
  );
}

function claudeCodeTask(ctx) {
  return (
    `# Tabatha Cortex — Nightly Workflow Optimization\n\n` +
    `This is an automated scheduled task generated by Tabatha (Cortex C6/C8 tier-①, cron-in-harness). ` +
    `Runs daily (${ctx.scheduleHint || '03:30 local'}). The user is not present; work autonomously and ` +
    `produce the recommendations file only — do not modify other files or systems.\n\n` +
    `## Task\n\n${sharedContract(ctx)}\n`
  );
}

function codexBody(ctx) {
  return `## Task\n\n${sharedContract(ctx)}`;
}

/**
 * Phase 4 (Plan 043 T2) — the proactive overnight EXECUTOR bundle.
 * A second scheduled task that reads the day's `cortex-actions-<day>.json`
 * (schema cortex-actions.v1, written by EXPORT_APPROVED_ACTIONS) and
 * generates the artifacts into a review directory. Hard guardrails are
 * baked into the task text: only `proactive: true` actions run, and
 * generated code is NEVER installed — everything lands as review files.
 */
export function buildExecuteBundle({ harness, actionsDir, reviewDir, scheduleHint }) {
  const body =
    `# Tabatha Cortex — Overnight Action Executor\n\n` +
    `Automated scheduled task generated by Tabatha (Cortex C7/C8, proactive mode). ` +
    `Runs daily (${scheduleHint || '04:30 local'}), AFTER the optimization pass. The user is ` +
    `not present; work autonomously and write review artifacts only.\n\n` +
    `## Task\n\n` +
    `1. Read the NEWEST \`cortex-actions-*.json\` in \`${actionsDir}\` (schema \`cortex-actions.v1\`).\n` +
    `2. Execute ONLY actions with \`proactive: true\`. Skip everything else — the user has not ` +
    `authorized overnight execution for those.\n` +
    `3. For each action, follow its \`prompt\` and write the output to ` +
    `\`${reviewDir}\\<recommendationId>\\\` (one folder per action: the artifact plus a short README ` +
    `explaining what it is and how to apply it).\n` +
    `4. HARD RULES: never install anything, never modify Tabatha or any other software, never run ` +
    `generated code — you draft, the user reviews in the morning. Actions with ` +
    `\`reviewRequired: true\` must lead their README with a review checklist.\n` +
    `5. Write a summary \`${reviewDir}\\morning-review-<day>.md\` listing every artifact produced ` +
    `and every action skipped (with the reason).\n`;

  if (harness === 'claude-code') {
    return {
      harness,
      files: [{ relPath: 'scheduled-tasks/tabatha-cortex-execute/SKILL.md', content: body }],
      instructions:
        `Copy the 'scheduled-tasks' folder into your Claude Code home (%USERPROFILE%\\.claude\\) ` +
        `and schedule it daily around ${scheduleHint || '04:30'} — after the optimize task.`
    };
  }
  if (harness === 'codex') {
    return {
      harness,
      files: [{ relPath: 'tabatha-cortex-execute.md', content: body }],
      instructions: `Register as a recurring Codex task, daily around ${scheduleHint || '04:30'}.`
    };
  }
  throw new Error(`buildExecuteBundle: unknown harness "${harness}"`);
}

/** Validate one recommendation record against the v1 contract. */
export function validateRecommendation(rec) {
  const errors = [];
  if (!rec || typeof rec !== 'object') return { ok: false, errors: ['not an object'] };
  if (!rec.id) errors.push('missing id');
  if (!rec.title) errors.push('missing title');
  if (!rec.rationale) errors.push('missing rationale');
  if (!RECOMMENDATION_TYPES.includes(rec.type)) errors.push(`unknown type "${rec.type}"`);
  if (!RECOMMENDATION_STATUSES.includes(rec.status)) errors.push(`unknown status "${rec.status}"`);
  return { ok: errors.length === 0, errors };
}

/**
 * Normalize a harness-produced recommendations payload for import into the
 * dashboard store. Lenient: accepts the envelope or a bare array; generates
 * ids; stamps importedAt; forces status to 'pending'; splits invalid rows out.
 */
export function normalizeRecommendations(payload, { now }) {
  let rows;
  if (Array.isArray(payload)) {
    rows = payload;
  } else if (payload && payload.schema === RECOMMENDATIONS_SCHEMA) {
    rows = payload.recommendations || [];
  } else {
    throw new Error(
      `normalizeRecommendations: expected schema "${RECOMMENDATIONS_SCHEMA}", got "${payload?.schema}"`
    );
  }

  const accepted = [];
  const rejected = [];
  rows.forEach((raw, i) => {
    const rec = {
      ...raw,
      id: raw?.id || `rec-${now}-${i}`,
      status: 'pending',
      importedAt: new Date(now).toISOString()
    };
    const { ok, errors } = validateRecommendation(rec);
    if (ok) accepted.push(rec);
    else rejected.push({ row: raw, errors });
  });
  return { accepted, rejected };
}
