import { formatDuration } from '../helpers.js';
import {
  getCategories,
  getClosedContexts,
  getSessions,
  getSettings,
  getSubGroups,
  getTabData,
  getTimeTracking,
  PRIORITY_LEVELS,
  setStorage,
} from './storageService.js';

let dependencies = {
  setTabData: async (tabs) => setStorage({ tabs }),
};

export function configureSessionService(overrides = {}) {
  dependencies = { ...dependencies, ...overrides };
}

export async function handleMessage(type, message) {
  switch (type) {
    case 'GET_SESSIONS':
      return { sessions: await getSessions() };
    case 'GET_CLOSED_CONTEXTS':
      return { closedContexts: await getClosedContexts() };
    case 'GET_FLOW_RECALL':
      return { flows: await getFlowRecallData() };
    case 'REOPEN_FLOW':
      return { tabIds: await reopenFlow(message.flowKey, message.newIntent) };
    case 'EXPORT_MARKDOWN': {
      const md = await exportMarkdown();
      return { success: true, content: md };
    }
    default:
      return null;
  }
}

async function getFlowRecallData() {
  const closedContexts = await getClosedContexts();
  const subGroups = await getSubGroups();

  // Group closed contexts by sub-group or context.
  const flows = {};
  for (const ctx of closedContexts) {
    const key = ctx.subGroupId || ctx.context || 'ungrouped';
    if (!flows[key]) {
      flows[key] = {
        context: ctx.context,
        intent: ctx.intent,
        subGroupId: ctx.subGroupId,
        subGroupName: ctx.subGroupId ? subGroups[ctx.subGroupId]?.name : null,
        tabs: []
      };
    }
    flows[key].tabs.push(ctx);
  }

  return flows;
}

async function reopenFlow(flowKey, newSessionIntent) {
  const { setTabData } = dependencies;
  const flows = await getFlowRecallData();
  const flow = flows[flowKey];
  if (!flow) return;

  const tabIds = [];
  for (const ctx of flow.tabs) {
    if (ctx.url) {
      const tab = await chrome.tabs.create({ url: ctx.url, active: false });
      tabIds.push(tab.id);

      // Restore context on the new tab.
      const tabs = await getTabData();
      if (tabs[tab.id]) {
        tabs[tab.id].context = ctx.context;
        tabs[tab.id].intent = newSessionIntent || ctx.intent;
        tabs[tab.id].priority = ctx.priority;
        tabs[tab.id].category = ctx.category;
        await setTabData(tabs);
      }
    }
  }

  return tabIds;
}

async function exportMarkdown() {
  const tabs = await getTabData();
  const subGroups = await getSubGroups();
  const categories = await getCategories();
  const closedContexts = await getClosedContexts();
  const timeTracking = await getTimeTracking();
  const settings = await getSettings();

  let md = `# Tabatha Context â€” ${new Date().toLocaleString()}\n\n`;
  md += `> Auto-generated by Tabatha. Designed for AI agent consumption.\n\n`;

  // Active tabs by group.
  md += `## Active Tabs (${Object.keys(tabs).length})\n\n`;

  const grouped = {};
  for (const [tabId, tab] of Object.entries(tabs)) {
    const key = tab.subGroupId || tab.groupId || 'ungrouped';
    if (!grouped[key]) grouped[key] = [];
    grouped[key].push({ tabId, ...tab });
  }

  for (const [groupKey, groupTabs] of Object.entries(grouped)) {
    const groupName = subGroups[groupKey]?.name || `Group ${groupKey}`;
    md += `### ${groupKey === 'ungrouped' ? 'Ungrouped' : groupName}\n\n`;

    for (const tab of groupTabs) {
      const priority = PRIORITY_LEVELS[tab.priority]?.label || 'âšª None';
      const catIcon = categories[tab.category]?.icon || 'â“';
      const time = formatDuration(tab.activeTime || 0);
      const locked = tab.locked ? 'ðŸ”’' : '';
      const urlLocked = tab.urlLocked ? 'ðŸ”—' : '';

      md += `- ${priority} ${catIcon} ${locked}${urlLocked} **${tab.title}**\n`;
      md += `  - URL: ${tab.url}\n`;
      if (tab.context) md += `  - Context: ${tab.context}\n`;
      if (tab.intent) md += `  - Intent: ${tab.intent}\n`;
      md += `  - Active time: ${time}\n`;
      md += `  - Opened: ${tab.openedAt}\n\n`;
    }
  }

  // Closed contexts.
  if (closedContexts.length > 0) {
    md += `## Recently Closed Contexts\n\n`;
    for (const ctx of closedContexts.slice(0, 20)) {
      md += `- **${ctx.title}** (${ctx.priority})\n`;
      if (ctx.context) md += `  - Context: ${ctx.context}\n`;
      md += `  - URL: ${ctx.url}\n`;
      md += `  - Closed: ${ctx.closedAt}\n\n`;
    }
  }

  // Time summary.
  md += `## Time Summary\n\n`;
  md += `| Category | Time |\n|----------|------|\n`;
  for (const [cat, ms] of Object.entries(timeTracking.byCategory)) {
    const catName = categories[cat]?.name || cat;
    md += `| ${catName} | ${formatDuration(ms)} |\n`;
  }
  md += `\n`;

  // Download the file.
  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);

  chrome.downloads.download({
    url,
    filename: `${settings.exportPath}/context.md`,
    saveAs: false,
    conflictAction: 'overwrite'
  });

  return md;
}
