// ════════════════════════════════════════════
// Tabatha — Session Service (Plan 023 Task 03)
// Owns session snapshots, closed-context recall, flow restore, and the
// markdown context export. Cap enforcement (snapshot/closed-context counts)
// is driven by settings.storage.* with archive-before-trim.
// ════════════════════════════════════════════

import {
  getStorage,
  setStorage,
  getSettings,
  getSessions,
  getClosedContexts,
  getCategories,
  getTabData,
  getSubGroups,
  getTimeTracking,
  enforceArrayCap
} from './storageService.js';
import { archiveBeforeCap } from './archiveService.js';
import { formatDuration } from '../helpers.js';
import { PRIORITY_LEVELS } from '../constants.js';

let injectedDeps = {};

export function configureSessionService(deps = {}) {
  injectedDeps = { ...injectedDeps, ...deps };
}

export async function handleMessage(type, message) {
  switch (type) {
    case 'GET_SESSIONS':
      return { sessions: await getSessions() };

    case 'GET_LATEST_SESSION': {
      const sessions = await getSessions();
      return { session: sessions[0] || null };
    }

    case 'GET_CLOSED_CONTEXTS':
      return { closedContexts: await getClosedContexts() };

    case 'GET_FLOW_RECALL':
      return { flows: await getFlowRecallData() };

    case 'REOPEN_FLOW':
      return { tabIds: await reopenFlow(message.flowKey, message.newIntent) };

    case 'EXPORT_MARKDOWN': {
      const content = await exportMarkdown();
      return { success: true, content };
    }

    default:
      return undefined;
  }
}

// ── Closed contexts ──
// Capped via settings.storage.closedContextsCap with archive-before-trim.
export async function appendClosedContext(entry) {
  const closedContexts = await getClosedContexts();
  closedContexts.unshift(entry);
  await setStorage({ closedContexts });

  const { dropped } = await enforceArrayCap('closedContexts', 'closedContextsCap');
  if (dropped.length) {
    await archiveBeforeCap('closedContexts', dropped, 'localArchive');
  }
  return closedContexts;
}

// ── Flow recall ──
async function getFlowRecallData() {
  const closedContexts = await getClosedContexts();
  const subGroups = await getSubGroups();

  const flows = {};
  for (const ctx of closedContexts) {
    const key = ctx.subGroupId || ctx.context || 'ungrouped';
    if (!flows[key]) {
      flows[key] = {
        context: ctx.context,
        intent: ctx.intent,
        subGroupId: ctx.subGroupId,
        subGroupName: ctx.subGroupId ? subGroups[ctx.subGroupId]?.name : null,
        tabs: []
      };
    }
    flows[key].tabs.push(ctx);
  }

  return flows;
}

async function reopenFlow(flowKey, newSessionIntent) {
  const flows = await getFlowRecallData();
  const flow = flows[flowKey];
  if (!flow) return [];

  const setTabData = injectedDeps.setTabData
    || (async (tabs) => setStorage({ tabs }));

  const tabIds = [];
  for (const ctx of flow.tabs) {
    if (!ctx.url) continue;
    const tab = await chrome.tabs.create({ url: ctx.url, active: false });
    tabIds.push(tab.id);

    const tabs = await getTabData();
    if (tabs[tab.id]) {
      tabs[tab.id].context = ctx.context;
      tabs[tab.id].intent = newSessionIntent || ctx.intent;
      tabs[tab.id].priority = ctx.priority;
      tabs[tab.id].category = ctx.category;
      await setTabData(tabs);
    }
  }
  return tabIds;
}

// ── Snapshots ──
export async function saveSessionSnapshot() {
  const tabs = await getTabData();
  const sessions = await getSessions();
  const snapshot = {
    snapshotAt: new Date().toISOString(),
    tabCount: Object.keys(tabs).length,
    tabs: { ...tabs }
  };
  sessions.unshift(snapshot);
  await setStorage({ sessions });

  const { dropped } = await enforceArrayCap('sessions', 'snapshotCap');
  if (dropped.length) {
    await archiveBeforeCap('sessions', dropped, 'localArchive');
  }
}

// ── Markdown export ──
export async function exportMarkdown() {
  const tabs = await getTabData();
  const subGroups = await getSubGroups();
  const categories = await getCategories();
  const closedContexts = await getClosedContexts();
  const timeTracking = await getTimeTracking();
  const settings = await getSettings();

  let md = `# Tabatha Context — ${new Date().toLocaleString()}\n\n`;
  md += `> Auto-generated by Tabatha. Designed for AI agent consumption.\n\n`;

  md += `## Active Tabs (${Object.keys(tabs).length})\n\n`;

  const grouped = {};
  for (const [tabId, tab] of Object.entries(tabs)) {
    const key = tab.subGroupId || tab.groupId || 'ungrouped';
    if (!grouped[key]) grouped[key] = [];
    grouped[key].push({ tabId, ...tab });
  }

  for (const [groupKey, groupTabs] of Object.entries(grouped)) {
    const groupName = subGroups[groupKey]?.name || `Group ${groupKey}`;
    md += `### ${groupKey === 'ungrouped' ? 'Ungrouped' : groupName}\n\n`;

    for (const tab of groupTabs) {
      const priority = PRIORITY_LEVELS[tab.priority]?.label || '⚪ None';
      const catIcon = categories[tab.category]?.icon || '❓';
      const time = formatDuration(tab.activeTime || 0);
      const locked = tab.locked ? '🔒' : '';
      const urlLocked = tab.urlLocked ? '🔗' : '';

      md += `- ${priority} ${catIcon} ${locked}${urlLocked} **${tab.title}**\n`;
      md += `  - URL: ${tab.url}\n`;
      if (tab.context) md += `  - Context: ${tab.context}\n`;
      if (tab.intent) md += `  - Intent: ${tab.intent}\n`;
      md += `  - Active time: ${time}\n`;
      md += `  - Opened: ${tab.openedAt}\n\n`;
    }
  }

  if (closedContexts.length > 0) {
    md += `## Recently Closed Contexts\n\n`;
    for (const ctx of closedContexts.slice(0, 20)) {
      md += `- **${ctx.title}** (${ctx.priority})\n`;
      if (ctx.context) md += `  - Context: ${ctx.context}\n`;
      md += `  - URL: ${ctx.url}\n`;
      md += `  - Closed: ${ctx.closedAt}\n\n`;
    }
  }

  md += `## Time Summary\n\n`;
  md += `| Category | Time |\n|----------|------|\n`;
  for (const [cat, ms] of Object.entries(timeTracking.byCategory)) {
    const catName = categories[cat]?.name || cat;
    md += `| ${catName} | ${formatDuration(ms)} |\n`;
  }
  md += `\n`;

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);

  chrome.downloads.download({
    url,
    filename: `${settings.exportPath}/context.md`,
    saveAs: false,
    conflictAction: 'overwrite'
  });

  return md;
}
